// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID          int32       `json:"id"`
	TopicID     pgtype.UUID `json:"topic_id"`
	Description string      `json:"description"`
	PhotoUrl    pgtype.Text `json:"photo_url"`
}

type ItemValue struct {
	ID     int32  `json:"id"`
	ItemID int32  `json:"item_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type Record struct {
	ID        int32       `json:"id"`
	VoterID   pgtype.UUID `json:"voter_id"`
	ItemID    int32       `json:"item_id"`
	CreatedAt int32       `json:"created_at"`
}

type Topic struct {
	ID        pgtype.UUID `json:"id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	Name      string      `json:"name"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
	CreatedAt int32       `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID `json:"id"`
	UserName       string      `json:"user_name"`
	HashedPassword string      `json:"hashed_password"`
}

type Voter struct {
	ID      pgtype.UUID `json:"id"`
	TopicID pgtype.UUID `json:"topic_id"`
}
