// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Item struct {
	ID          int32          `json:"id"`
	TopicID     uuid.UUID      `json:"topic_id"`
	Description string         `json:"description"`
	PhotoUrl    sql.NullString `json:"photo_url"`
}

type ItemValue struct {
	ID     int32  `json:"id"`
	ItemID int32  `json:"item_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type Record struct {
	ID        int32 `json:"id"`
	VoterID   int32 `json:"voter_id"`
	ItemID    int32 `json:"item_id"`
	CreatedAt int32 `json:"created_at"`
}

type Topic struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	StartAt   int32     `json:"start_at"`
	ExpiredAt int32     `json:"expired_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	UserName       string    `json:"user_name"`
	HashedPassword string    `json:"hashed_password"`
}

type Voter struct {
	ID         int32     `json:"id"`
	UserName   string    `json:"user_name"`
	TopicID    uuid.UUID `json:"topic_id"`
	PrivateKey string    `json:"private_key"`
}
