// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (topic_id, description)
VALUES ($1, $2)
RETURNING id
`

type CreateItemParams struct {
	TopicID     pgtype.UUID `json:"topic_id"`
	Description string      `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createItem, arg.TopicID, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createItemValue = `-- name: CreateItemValue :one
INSERT INTO item_values (item_id, key, value)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateItemValueParams struct {
	ItemID int32  `json:"item_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) CreateItemValue(ctx context.Context, arg CreateItemValueParams) (int32, error) {
	row := q.db.QueryRow(ctx, createItemValue, arg.ItemID, arg.Key, arg.Value)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (owner_id, start_at, expired_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTopicParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.OwnerID, arg.StartAt, arg.ExpiredAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createVoter = `-- name: CreateVoter :one
INSERT INTO voters (topic_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateVoter(ctx context.Context, topicID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVoter, topicID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTopicOwner = `-- name: GetTopicOwner :one
SELECT owner_id
FROM topics
WHERE id = $1
`

func (q *Queries) GetTopicOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTopicOwner, id)
	var owner_id pgtype.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const updateItemPhotoUrl = `-- name: UpdateItemPhotoUrl :exec
UPDATE items
SET photo_url = $2
WHERE id = $1
`

type UpdateItemPhotoUrlParams struct {
	ID       int32       `json:"id"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

func (q *Queries) UpdateItemPhotoUrl(ctx context.Context, arg UpdateItemPhotoUrlParams) error {
	_, err := q.db.Exec(ctx, updateItemPhotoUrl, arg.ID, arg.PhotoUrl)
	return err
}
