// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItemsByTopic = `-- name: CountItemsByTopic :one
SELECT COUNT(*) AS item_count
FROM items
WHERE topic_id = $1
`

func (q *Queries) CountItemsByTopic(ctx context.Context, topicID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByTopic, topicID)
	var item_count int64
	err := row.Scan(&item_count)
	return item_count, err
}

const countVotersByTopic = `-- name: CountVotersByTopic :one
SELECT COUNT(*) AS voter_count
FROM voters
WHERE topic_id = $1
`

func (q *Queries) CountVotersByTopic(ctx context.Context, topicID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotersByTopic, topicID)
	var voter_count int64
	err := row.Scan(&voter_count)
	return voter_count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (topic_id, description)
VALUES ($1, $2)
RETURNING id
`

type CreateItemParams struct {
	TopicID     pgtype.UUID `json:"topic_id"`
	Description string      `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createItem, arg.TopicID, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createItemValue = `-- name: CreateItemValue :one
INSERT INTO item_values (item_id, key, value)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateItemValueParams struct {
	ItemID int32  `json:"item_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) CreateItemValue(ctx context.Context, arg CreateItemValueParams) (int32, error) {
	row := q.db.QueryRow(ctx, createItemValue, arg.ItemID, arg.Key, arg.Value)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (owner_id, name, start_at, expired_at, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTopicParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	Name      string      `json:"name"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
	CreatedAt int32       `json:"created_at"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.OwnerID,
		arg.Name,
		arg.StartAt,
		arg.ExpiredAt,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createVoter = `-- name: CreateVoter :one
INSERT INTO voters (topic_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateVoter(ctx context.Context, topicID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVoter, topicID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getItemById = `-- name: GetItemById :one
SELECT id, topic_id, description
FROM items
WHERE id = $1
`

type GetItemByIdRow struct {
	ID          int32       `json:"id"`
	TopicID     pgtype.UUID `json:"topic_id"`
	Description string      `json:"description"`
}

func (q *Queries) GetItemById(ctx context.Context, id int32) (GetItemByIdRow, error) {
	row := q.db.QueryRow(ctx, getItemById, id)
	var i GetItemByIdRow
	err := row.Scan(&i.ID, &i.TopicID, &i.Description)
	return i, err
}

const getItemPhotoUrl = `-- name: GetItemPhotoUrl :one
SELECT photo_url
FROM items
WHERE id = $1
`

func (q *Queries) GetItemPhotoUrl(ctx context.Context, id int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getItemPhotoUrl, id)
	var photo_url pgtype.Text
	err := row.Scan(&photo_url)
	return photo_url, err
}

const getItemValuesByTopic = `-- name: GetItemValuesByTopic :many
SELECT item_values.id, item_values.item_id, item_values.key, item_values.value
FROM item_values
JOIN items ON items.id = item_values.item_id
WHERE items.topic_id = $1
`

func (q *Queries) GetItemValuesByTopic(ctx context.Context, topicID pgtype.UUID) ([]ItemValue, error) {
	rows, err := q.db.Query(ctx, getItemValuesByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemValue
	for rows.Next() {
		var i ItemValue
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByTopic = `-- name: GetItemsByTopic :many
SELECT id, description
FROM items
WHERE topic_id = $1
`

type GetItemsByTopicRow struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

func (q *Queries) GetItemsByTopic(ctx context.Context, topicID pgtype.UUID) ([]GetItemsByTopicRow, error) {
	rows, err := q.db.Query(ctx, getItemsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByTopicRow
	for rows.Next() {
		var i GetItemsByTopicRow
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicById = `-- name: GetTopicById :one
SELECT id, name, start_at, expired_at, created_at
FROM topics
WHERE id = $1
`

type GetTopicByIdRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
	CreatedAt int32       `json:"created_at"`
}

func (q *Queries) GetTopicById(ctx context.Context, id pgtype.UUID) (GetTopicByIdRow, error) {
	row := q.db.QueryRow(ctx, getTopicById, id)
	var i GetTopicByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicOwner = `-- name: GetTopicOwner :one
SELECT owner_id
FROM topics
WHERE id = $1
`

func (q *Queries) GetTopicOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTopicOwner, id)
	var owner_id pgtype.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getTopicsByOwner = `-- name: GetTopicsByOwner :many
SELECT id, name, start_at, expired_at, created_at
FROM topics
WHERE owner_id = $1
`

type GetTopicsByOwnerRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
	CreatedAt int32       `json:"created_at"`
}

func (q *Queries) GetTopicsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]GetTopicsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getTopicsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopicsByOwnerRow
	for rows.Next() {
		var i GetTopicsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartAt,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotersByTopic = `-- name: GetVotersByTopic :many
SELECT id
FROM voters
WHERE topic_id = $1
`

func (q *Queries) GetVotersByTopic(ctx context.Context, topicID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getVotersByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemPhotoUrl = `-- name: UpdateItemPhotoUrl :exec
UPDATE items
SET photo_url = $2
WHERE id = $1
`

type UpdateItemPhotoUrlParams struct {
	ID       int32       `json:"id"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

func (q *Queries) UpdateItemPhotoUrl(ctx context.Context, arg UpdateItemPhotoUrlParams) error {
	_, err := q.db.Exec(ctx, updateItemPhotoUrl, arg.ID, arg.PhotoUrl)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics
SET name = $2, start_at = $3, expired_at = $4
WHERE id = $1
`

type UpdateTopicParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	StartAt   int32       `json:"start_at"`
	ExpiredAt int32       `json:"expired_at"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic,
		arg.ID,
		arg.Name,
		arg.StartAt,
		arg.ExpiredAt,
	)
	return err
}
