// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const login = `-- name: Login :one
SELECT id, hashed_password
FROM users
WHERE user_name = $1
`

type LoginRow struct {
	ID             pgtype.UUID `json:"id"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) Login(ctx context.Context, userName string) (LoginRow, error) {
	row := q.db.QueryRow(ctx, login, userName)
	var i LoginRow
	err := row.Scan(&i.ID, &i.HashedPassword)
	return i, err
}

const signup = `-- name: Signup :one
INSERT INTO users (user_name, hashed_password)
VALUES ($1, $2)
RETURNING id
`

type SignupParams struct {
	UserName       string `json:"user_name"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, signup, arg.UserName, arg.HashedPassword)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
