// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVotesByItem = `-- name: CountVotesByItem :one
SELECT COUNT(*) AS vote_count
FROM records
WHERE item_id = $1
`

func (q *Queries) CountVotesByItem(ctx context.Context, itemID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesByItem, itemID)
	var vote_count int64
	err := row.Scan(&vote_count)
	return vote_count, err
}

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (voter_id, item_id, created_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateRecordParams struct {
	VoterID   pgtype.UUID `json:"voter_id"`
	ItemID    int32       `json:"item_id"`
	CreatedAt int32       `json:"created_at"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRecord, arg.VoterID, arg.ItemID, arg.CreatedAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getVoterById = `-- name: GetVoterById :one
SELECT id, topic_id
FROM voters
WHERE id = $1
`

func (q *Queries) GetVoterById(ctx context.Context, id pgtype.UUID) (Voter, error) {
	row := q.db.QueryRow(ctx, getVoterById, id)
	var i Voter
	err := row.Scan(&i.ID, &i.TopicID)
	return i, err
}
